export const FETCH_BOOKS_START = 'FETCH_BOOKS_START'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR'

export const SEARCH_BY_PARAMS_BOOKS_START = 'SEARCH_BY_PARAMS_BOOKS_START'
export const SEARCH_BY_PARAMS_BOOKS_SUCCESS = 'SEARCH_BY_PARAMS_BOOKS_SUCCESS'
export const SEARCH_BY_PARAMS_BOOKS_ERROR = 'SEARCH_BY_PARAMS_BOOKS_ERROR'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const AUTHORIZATION_USER_SUCCESS = 'AUTHORIZATION_USER_SUCCESS'
export const AUTHORIZATION_USER_ERROR = 'AUTHORIZATION_USER_ERROR'
export const AUTHORIZATION_AUTO_LOGOUT = 'AUTHORIZATION_AUTO_LOGOUT'