require:
  - rubocop-rails

AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - db/schema.rb
    - tmp/**/*
    - config/**/*
  ExtraDetails: true
  TargetRubyVersion: 2.7.2

Layout/TrailingWhitespace:
  Severity: warning

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining


Layout/TrailingEmptyLines:
  Severity: warning

Layout/EmptyLines:
  Severity: warning

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Enabled: false
  Max: 120

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/NumericPredicate:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LeadingCommentSpace:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"
    "%i": "()"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Rails/ActionFilter:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false

Rails/ActiveRecordOverride:
  Enabled: false

Rails/ActiveSupportAliases:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/AssertNot:
  Enabled: false

Rails/BelongsTo:
  Enabled: false

Rails/Blank:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/DelegateAllowBlank:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Rails/EnumUniqueness:
  Enabled: false

Rails/EnvironmentComparison:
  Enabled: false

Rails/Exit:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/IgnoredSkipActionFilterOption:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/LinkToBlank:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/PluralizationGrammar:
  Enabled: true
  Severity: warning

Rails/Presence:
  Enabled: true
  Severity: warning

Rails/Present:
  Enabled: true
  NotNilAndNotEmpty: true
  NotBlank: true
  UnlessBlank: true
  Severity: warning

Rails/ReadWriteAttribute:
  Enabled: false

Rails/RedundantAllowNil:
  Enabled: false

Rails/RedundantReceiverInWithOptions:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/RelativeDateConstant:
  Enabled: false

Rails/RequestReferer:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/SafeNavigation:
  Enabled: false

Rails/ScopeArgs:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqBeforePluck:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Rails/Date:
  Enabled: true
  Details: >-
    `Prefer Date.current instead of Date.today`

Rails/TimeZone:
  Enabled: true
  Details: >-
    `Prefer Time.current instead of Time.zone.now`

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
  ExpectedOrder:
    - include
    - prepend
    - extend

    - constants

    - attribute
    - attr_reader
    - attr_writer
    - attr_accessor

    - belongs_to
    - has_one
    - has_many
    - has_and_belongs_to_many

    - validates
    - validate

    - before_validation
    - after_validation
    - before_save
    - around_save
    - before_create
    - around_create
    - after_create
    - before_update
    - around_update
    - after_update
    - after_save
    - before_destroy
    - around_destroy
    - after_destroy
    - after_commit

    - default_scope
    - scope
    - class_methods
    - public_methods
    - protected_methods
    - private_methods
