json.extract! @user,
              :first_name,
              :last_name,
              :email,
              :csrf_token,
              :access_token,
              :access_token_expired_at,
              :refresh_token,
              :refresh_token_expires_at,
              :current_sign_in_ip,
              :last_sign_in_ip
